# Esto sirve para escribir GRANDE

Sin "gato" escribimos en pequeño


# Empezando a programar
Esta es la primera clase

In [4]:
#from pylab import *
#%matplotlib inline

# Integer, Float y Double

In [8]:
#1 es Integer... te da operaciones con enteros.
#1. es un Float... significa que cada numero puedes tomarlo 
#En el caso de python3 reconoce a todos los numeros como floats

In [9]:
1/2

0.5

In [11]:
#* es por y ** elevar

In [12]:
a=1
b=2
c=3

In [13]:
a+b

3

In [14]:
a-c

-2

In [15]:
sqrt(b)

NameError: name 'sqrt' is not defined

# VECTORES

In [24]:
Vector1 = [1,2,3,4]
print (Vector1[1])
c = Vector1[2]/2
print (c)

print ("la primera entrada es", Vector1[0], "la segunda entrada es", Vector1[1])

2
1.5
la primera entrada es 1 la segunda entrada es 2


In [25]:
print (Vector1)

[1, 2, 3, 4]


In [26]:
array([1,2,3,4])

NameError: name 'array' is not defined

In [27]:
a = ["Hola", [1,2,3], 507, 0.3] #La lista debe estar en corchetes.

In [28]:
a[0]

'Hola'

In [29]:
zeros(5)

NameError: name 'zeros' is not defined

In [ ]:
from pylab import *
%>>> %matplotlib inline
  File "<stdin>", line 1
    %matplotlib inline
    ^
SyntaxError: invalid syntax
>>> import matplotlib
>>> a=1
>>> b=2
>>> c=
  File "<stdin>", line 1
    c=
     ^
SyntaxError: invalid syntax
>>> c=3
>>> sqrt(b)
1.4142135623730951
>>> a+b
3
>>> 4**(0.5)
2.0
>>> #VECTORES
... 
>>> Vector1 = (1,2,3,4)
>>> Vector1 =[1,2,3,4]
>>> print Vector1[1]
2
>>> array([1,2,3,4])
array([1, 2, 3, 4])
>>> a = ["Hola", [1,2,3], 507, 0.3]
>>> a[0]
'Hola'
>>> 
KeyboardInterrupt
>>> zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])
>>> zeros(2,5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: data type not understood
>>> zeros((2,5))
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])
>>> ones(3)
array([ 1.,  1.,  1.])
>>> ones(8)
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
>>> vector2 = ones(8)
>>> vector2[5] = 7
>>> print vector2
[ 1.  1.  1.  1.  1.  7.  1.  1.]
>>> vector2[5:7] = 7
>>> print vector2
[ 1.  1.  1.  1.  1.  7.  7.  1.]
>>> vector2[:5-1] =7
>>> 
>>> print vector2
[ 7.  7.  7.  7.  1.  7.  7.  1.]
>>> vector2[0:5-1] = [11,12,13,14]
>>> print vector2
[ 11.  12.  13.  14.   1.   7.   7.   1.]
>>> vector3 = [1,2,3,4,5,6]
>>> vector3[2:4] = [11,12]
>>> print vector3
[1, 2, 11, 12, 5, 6]
>>> matriz1 = [[1,2,3],[4,5,6],[7,8,9][
... 
... 
... matriz1 = [[1,2,3],[4,5,6],[7,8,9]]
  File "<stdin>", line 4
    matriz1 = [[1,2,3],[4,5,6],[7,8,9]]
            ^
SyntaxError: invalid syntax
>>> matriz1 = [[1,2,3],[4,5,6],[7,8,9]]
>>> print matriz1[0]
[1, 2, 3]
>>> print matriz1[0][0]
1
>>> print matriz1[1][2]
6
>>> print matriz1[1,2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list indices must be integers, not tuple
>>> matriz2 = zeros((3,3))
>>> print matriz2
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
>>> matriz2[1,1]
0.0
>>> matriz[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'matriz' is not defined
>>> matriz2[0]
array([ 0.,  0.,  0.])
>>> matriz2[1,1] = 5
>>> matriz2
array([[ 0.,  0.,  0.],
       [ 0.,  5.,  0.],
       [ 0.,  0.,  0.]])
